### ISSUE TITLE
P2D does not work

### ISSUE THREAD

**Issue by mrBirrell** [Abdulla060/Processing.py-intellisense#1]
Hello, when calling:

    size(1280, 720, P2D)

There is an error in the external tool:

java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\USER\Documents\ProcessingPy\natives\windows-i586\\gluegen-rt.dll

Is there a work around for this, or will P2D just not work?  I know in intelliJ I have to add the other JAR files to get P2D to work, but I am not sure how this works in PyCharm.

**Comment by Abdulla060** [comment]
Hello, when I was making this project, I thought I only needed the `processing-py.jar` file in order to run sketches. turns out I was wrong. I've just added the missing files back and everything works. you can download the zip file again. note: the only thing that changes is the `lib` folder you can extract that alone and add it to your existing project.

**Comment by mrBirrell** [comment]
Hi,  I am still getting this error:

java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\USERNAME\Documents\ProcessingPyTake2\natives\windows-i586\\gluegen-rt.dll

Do I need to add the libraries in pyCharm somehow besides extracting them into the directory?  I have tried extracting to my existing project as well as making a new one with your updated files but still get the same error.

All that I have changed to get the error is this:

size(512, 512, P2D)

**Comment by Abdulla060** [comment]
that is weird. I just installed PyCharm on a fresh copy of Ubuntu and I couldn't replicate your issue. which leads me to believe that there is some mistake in your config. try to run this command in a PyCharm terminal `java -jar lib/processing-py.jar {your sketch name}`. if you the issue goes away than double check your config or start a fresh copy. also, what are the contents of the `lib` folder? there should be many files and folders now.
edit: also forgot to mention. the python interpreter does nothing when it comes to running sketches. its there only so that PyCharm doesn't complain. sketches are ONLY run using processing-py.jar in the `lib` folder

**Comment by mrBirrell** [comment]
Yeah, running from the terminal gave the same error:

java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\n.birrell\Documents\ProcessingPyTake2\natives\windows-i586\\gluegen-rt.dll

There error is coming from Java in the External Tool window.

However, the problem was on my end and may be of use to other Wiindows users:

I am using my work-provided computer and it had a 32-bit JRE installed.  Removing this and installing a 64-bit JRE solved the issue and P2D works great!

Hopefully removing the 32-bit JRE doesn't break my other projects, heh...

You may want to add a note in the instructions for windows users to make sure they have the 64-bit JRE as the java website defaults to the 32-bit one still for windows downloads.

Thanks for the great project!
